### ISSUE TITLE
users resourcesの中のmemberとcollectionのルーティング

### ISSUE THREAD

**Issue by shinofumijp** [yamaken124/playlist_app#1]
my_pageとかshowではダメだったのか？
my_favoritesとかはusers/:user_id/favoritesではだめだったのか？
my_xxx => users/:user_id/xxx

**Comment by yamk-yamk** [comment]
ダメじゃないですね
fav , playlist , profile , follow , follower のとこ全部
users/:user)id/xxx
っていう形にできます。修正します。

ちなみに、これをやるのは重複を省いてスマートな作りにするという認識でいいでしょうか。

**Comment by yamk-yamk** [comment]
修正したプルリク
https://github.com/yamaken124/playlist_app/pull/15
